// <auto-generated />
using System;
using AssetPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetPulse.Api.Data.Migrations
{
    [DbContext(typeof(AssetPulseDbContext))]
    partial class AssetPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetPulse.Api.Domain.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Status");

                    b.HasIndex("Status", "Severity");

                    b.ToTable("Alarms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Alarms_Message_Trimmed", "LEN([Message]) > 0 AND [Message] = LTRIM(RTRIM([Message]))");

                            t.HasCheckConstraint("CK_Alarms_Severity", "[Severity] IN ('Warning', 'Critical')");

                            t.HasCheckConstraint("CK_Alarms_Status", "[Status] IN ('Active', 'Acknowledged', 'Resolved')");

                            t.HasCheckConstraint("CK_Alarms_Timestamps", "([Status] = 'Active' AND [AcknowledgedAt] IS NULL AND [ResolvedAt] IS NULL) OR ([Status] = 'Acknowledged' AND [AcknowledgedAt] IS NOT NULL AND [ResolvedAt] IS NULL) OR ([Status] = 'Resolved' AND [ResolvedAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AssetPulse.Api.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Pressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_AssetCode_Uppercase", "[AssetCode] COLLATE Latin1_General_100_BIN2 = UPPER([AssetCode]) COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_Assets_Pressure_Nonnegative", "[Pressure] IS NULL OR [Pressure] >= CONVERT(decimal(10, 2), 0)");

                            t.HasCheckConstraint("CK_Assets_RequiredText_Trimmed", "LEN([Name]) > 0 AND [Name] = LTRIM(RTRIM([Name])) AND LEN([AssetCode]) > 0 AND [AssetCode] = LTRIM(RTRIM([AssetCode])) AND LEN([Type]) > 0 AND [Type] = LTRIM(RTRIM([Type])) AND LEN([Location]) > 0 AND [Location] = LTRIM(RTRIM([Location]))");

                            t.HasCheckConstraint("CK_Assets_Temperature_AbsoluteZero", "[Temperature] IS NULL OR [Temperature] >= CONVERT(decimal(10, 2), -273.15)");
                        });
                });

            modelBuilder.Entity("AssetPulse.Api.Domain.AssetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Timestamp");

                    b.ToTable("AssetEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssetEvents_Description_Trimmed", "LEN([Description]) > 0 AND [Description] = LTRIM(RTRIM([Description]))");

                            t.HasCheckConstraint("CK_AssetEvents_NewStatus", "[NewStatus] IN ('Healthy', 'Warning', 'Critical')");

                            t.HasCheckConstraint("CK_AssetEvents_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] IN ('Healthy', 'Warning', 'Critical')");
                        });
                });

            modelBuilder.Entity("AssetPulse.Api.Domain.Alarm", b =>
                {
                    b.HasOne("AssetPulse.Api.Domain.Asset", "Asset")
                        .WithMany("Alarms")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetPulse.Api.Domain.AssetEvent", b =>
                {
                    b.HasOne("AssetPulse.Api.Domain.Asset", "Asset")
                        .WithMany("Events")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetPulse.Api.Domain.Asset", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
